### ISSUE TITLE
Date parsing bug

### ISSUE THREAD

**Issue by jonasbeckers** [EightyThreeCreative/ShineUpdater#3]
The parsing of a date from the xml file fails when your locale is not some variant of english. 
For example Tue, 10 April 2018 10:01:11 -0600 does not parse if your region is Belgium.
It might be better to choose an other dateformat that is not dependent on localization.

**Comment by Vortec4800** [comment]
My guess is the reason is that the parser is expecting the day and month to be in another language rather than English, is that correct?

I can force the parser date formatter localization to English regardless of the phone's current locale, so as long as the XML feed is always in English it will work. This won't result in any user-facing changes, only the XML date parser. Will that work?

**Comment by jonasbeckers** [comment]
Forcing english is okay for me.

**Comment by Vortec4800** [comment]
I pushed this change, try the head on the master and if it works I can do a release.

**Comment by jonasbeckers** [comment]
Works as expected.
